davcro_macbook_login: &davcro_macbook_login
  adapter: mysql2
  encoding: utf8
  username: root
  host: localhost
  socket: /tmp/mysql.sock

development:
  <<: *davcro_macbook_login
  database: efar_dispatch_dev

test:
  <<: *davcro_macbook_login
  database: efar_dispatch_test